.github/workflows/upload_doc.yaml
docs/canonical-identity-platform.md
docs/how-to-manual.md
docs/how-to/how-to-integrate-with-oidc-compatible-charms.md
docs/how-to/how-to-manage-external-identity-providers.md
docs/index.md

first try at a dry run with upload-charm-docs action

---

README.md

This is the first iteration of the Readme for this repository

added first iteration of the README

---

DOCS/canonical-identity-platform-explanation.md
DOCS/canonical-identity-platform-how-to-integrate-with-cos.md
DOCS/canonical-identity-platform-how-to-integrate-with-oidc-compatible-charms.md
DOCS/canonical-identity-platform-how-to-manage-external-identity-providers.md
DOCS/canonical-identity-platform-how-to-perform-database-migration-for-kratos-hydra.md
DOCS/canonical-identity-platform-how-to.md
DOCS/canonical-identity-platform-reference-architecture.md
DOCS/canonical-identity-platform-reference-hydra-observability.md
DOCS/canonical-identity-platform-reference-kratos-observability.md
DOCS/canonical-identity-platform-reference-login-flow.md
DOCS/canonical-identity-platform-reference-login-ui-observability.md
DOCS/canonical-identity-platform-reference.md
DOCS/canonical-identity-platform-tutorial-deploy-identity-bundle.md
DOCS/canonical-identity-platform-tutorials.md
DOCS/canonical-identity-platform.md
topic-ids.yaml

feat: added links to illustrations
feat: added pages to observability references
fix: updated topic-ids.yaml

feat: added links to references and navigation

---

.github/workflows/discourse-create.yaml
.github/workflows/discourse-sync.yaml
DOCS/canonical-identity-platform-tutorial-deploy-identity-bundle.md
README.md
add-table-of-contents/README.md
add-table-of-contents/main.py

New feature for the discourse-sync workflow. A table of contents section is added to each documents before they are synchronised.

feat: added add-table-of-contents script

---

DOCS/canonical-identity-platform.md
add-table-of-contents/main.py

fix: took out unused references from canonical-identity-platform.md

fix: added heading-- to anchors

---

DOCS/canonical-identity-platform-how-to.md
DOCS/canonical-identity-platform-reference.md
DOCS/canonical-identity-platform-tutorials.md

fix: fixes in docs

---

.github/workflows/discourse-sync.yaml
README.md

feat: discourse-sync workflow runs on push to main
feat: add usage to readme

fix-issues

---

CODEOWNERS
DOCS/openfga-how-to.md
DOCS/openfga-reference-openfga-observability.md
DOCS/openfga.md
README.md

IAM-827: OpenFGA starting docs

---

DOCS/openfga-reference-openfga-observability.md
DOCS/openfga-tutorial.md
DOCS/openfga.md

docs: adjust openfga style

---

.markdownlint.yaml
DOCS/glauth-tutorial.md
DOCS/glauth-utils-tutorial.md
DOCS/glauth-utils.md
topic-ids.yaml

This pull request tries to address the comments in the glauth-utils [charm review](https://discourse.charmhub.io/t/glauth-utils-charmhub-review/13922/3).

IAM-837 address the comments in the glauth-utils charm review

---

DOCS/hydra.md
DOCS/identity-platform-login-ui.md
DOCS/kratos-external-idp-integrator.md
DOCS/kratos.md

Link charm docs to charmhub topic

---

DOCS/glauth-tutorial.md
DOCS/glauth-utils-tutorial.md
DOCS/glauth-utils.md
DOCS/glauth.md

This pull request tries to fix the typos and navigation links.

docs: fix the dumb typos and documentation structure

---

.pre-commit-config.yaml
README.md
tox.ini

This pull request tries to add a conventional commit pre-commit hook.

chore: update pre-commit hooks

---

DOCS/openfga-how-to-integrate-with-openfga.md
DOCS/openfga-how-to.md
DOCS/openfga-tutorial.md
DOCS/openfga.md
topic-ids.yaml

Add how to page and how to integration guide

Update openfga docs

---

DOCS/openfga-explanation-security.md
DOCS/openfga-explanation.md
README.md
topic-ids.yaml

OpenFGA Charm Security document

---

DOCS/canonical-identity-platform-explanation-security.md
DOCS/canonical-identity-platform-explanation.md
DOCS/canonical-identity-platform.md
topic-ids.yaml

SSDLC requirement. Security documentation on the level of IdP bundle.

docs: added bundle level Identity Platform security documentation

---

.github/workflows/discourse-check.yaml
.github/workflows/discourse-create.yaml
.github/workflows/discourse-sync.yaml
DOCS/canonical-identity-platform.md
discourse-sync/main.py

This PR:
- switches to use a different discourse API key
- adds a dummy change to test if it works.

Switch discourse API key

---

.github/workflows/discourse-check.yaml
.github/workflows/discourse-create.yaml
.github/workflows/discourse-sync.yaml
discourse-sync/main.py

This reverts commit 22be3f7bd5dc5d0c76d040ea676dd5e24a717851.

Revert "ci: switch to use different api key"

---

DOCS/canonical-identity-platform-explanation.md
DOCS/canonical-identity-platform.md
DOCS/oauth2-oidc-explanation.md
topic-ids.yaml

Add oauth2/oidc explanation page

---

DOCS/canonical-identity-platform-tutorial-deploy-identity-bundle.md

The grafana url was missing the `-k8s` part.

Fix grafana url
